const mongoose = require('mongoose');


//  create a user schema
// here, the _id will be autogenerated by the MongoDB
const sauce = new mongoose.Schema({
    userId: {type: String, required: false},
    name: {type: String, required: true},
    manufacturer: {type: String, required: true},
    description: {type: String, required: true},
    mainPepper: {type: String, required: true},
    imageUrl: {type: String, required: true},
    heat: {type: Number, required: true},
    likes: {type: Number, required: false, default: 0},
    dislikes: {type: Number, required: false, default: 0},
    usersLiked: {type: Array, required: false, typeof: undefined},
    usersDisliked: {type: Array, required: false}
});


// Export the user with the 'User' name
module.exports = mongoose.model('Sauce', sauce);

